"""Create users table

Revision ID: d0a3ee3a0bef
Revises: 
Create Date: 2026-07-08 00:02:11.783980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0a3ee3a0bef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_equipped_item'), table_name='user_equipped_items')
    op.drop_index(op.f('idx_equipped_user'), table_name='user_equipped_items')
    op.drop_table('user_equipped_items')
    op.drop_index(op.f('ix_ege_subjects_id'), table_name='ege_subjects')
    op.drop_index(op.f('ix_ege_subjects_slug'), table_name='ege_subjects')
    op.drop_table('ege_subjects')
    op.drop_index(op.f('idx_article_views_article'), table_name='article_views')
    op.drop_index(op.f('idx_article_views_unique_daily'), table_name='article_views')
    op.drop_index(op.f('ix_article_views_article_id'), table_name='article_views')
    op.drop_index(op.f('ix_article_views_id'), table_name='article_views')
    op.drop_index(op.f('ix_article_views_user_id'), table_name='article_views')
    op.drop_table('article_views')
    op.drop_index(op.f('idx_test_results_test'), table_name='test_results')
    op.drop_index(op.f('idx_test_results_user'), table_name='test_results')
    op.drop_index(op.f('idx_test_results_user_test'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_lesson_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_test_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_user_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_table('language_categories')
    op.drop_index(op.f('idx_shop_items_active'), table_name='shop_items')
    op.drop_table('shop_items')
    op.drop_table('course_enrollments')
    op.drop_index(op.f('idx_comment_reactions_comment'), table_name='comment_reactions')
    op.drop_table('comment_reactions')
    op.drop_index(op.f('ix_language_lessons_category'), table_name='language_lessons')
    op.drop_table('language_lessons')
    op.drop_index(op.f('ix_course_teachers_course'), table_name='course_teachers')
    op.drop_index(op.f('ix_course_teachers_teacher'), table_name='course_teachers')
    op.drop_table('course_teachers')
    op.drop_index(op.f('idx_articles_slug'), table_name='articles')
    op.drop_index(op.f('idx_articles_topic'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('idx_article_reactions_article'), table_name='article_reactions')
    op.drop_index(op.f('idx_article_reactions_user'), table_name='article_reactions')
    op.drop_index(op.f('ix_article_reactions_article_id'), table_name='article_reactions')
    op.drop_index(op.f('ix_article_reactions_id'), table_name='article_reactions')
    op.drop_index(op.f('ix_article_reactions_user_id'), table_name='article_reactions')
    op.drop_table('article_reactions')
    op.drop_table('user_enrollments')
    op.drop_index(op.f('ix_rewards_type'), table_name='user_rewards')
    op.drop_index(op.f('ix_rewards_user'), table_name='user_rewards')
    op.drop_table('user_rewards')
    op.drop_index(op.f('idx_inventory_item'), table_name='user_inventory')
    op.drop_index(op.f('idx_inventory_user'), table_name='user_inventory')
    op.drop_table('user_inventory')
    op.drop_index(op.f('ix_flashcards_deck_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('idx_comments_article'), table_name='comments', postgresql_where='(article_id IS NOT NULL)')
    op.drop_index(op.f('idx_comments_lesson'), table_name='comments', postgresql_where='(lesson_id IS NOT NULL)')
    op.drop_index(op.f('idx_comments_parent'), table_name='comments')
    op.drop_index(op.f('ix_comments_article_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_lesson_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_user_completed_lessons_id'), table_name='user_completed_lessons')
    op.drop_table('user_completed_lessons')
    op.drop_index(op.f('ix_course_units_subject'), table_name='course_units')
    op.drop_table('course_units')
    op.drop_index(op.f('ix_language_lesson_reactions_lesson'), table_name='language_lesson_reactions')
    op.drop_index(op.f('ix_language_lesson_reactions_user'), table_name='language_lesson_reactions')
    op.drop_table('language_lesson_reactions')
    op.drop_table('language_subjects')
    op.drop_index(op.f('ix_enroll_course'), table_name='user_course_enrollments')
    op.drop_index(op.f('ix_enroll_user'), table_name='user_course_enrollments')
    op.drop_index(op.f('ix_user_course_enrollments_user'), table_name='user_course_enrollments')
    op.drop_table('user_course_enrollments')
    op.drop_index(op.f('idx_lesson_reactions_lesson'), table_name='lesson_reactions')
    op.drop_table('lesson_reactions')
    op.drop_index(op.f('idx_user_article_fav_article'), table_name='user_article_favorites')
    op.drop_index(op.f('idx_user_article_fav_user'), table_name='user_article_favorites')
    op.drop_table('user_article_favorites')
    op.drop_index(op.f('ix_language_comments_lesson'), table_name='language_comments')
    op.drop_table('language_comments')
    op.drop_index(op.f('ix_flashcard_progress_user'), table_name='flashcard_progress')
    op.drop_table('flashcard_progress')
    op.drop_index(op.f('ix_fav_course'), table_name='user_favorite_courses')
    op.drop_index(op.f('ix_fav_user'), table_name='user_favorite_courses')
    op.drop_index(op.f('ix_user_favorite_courses_course'), table_name='user_favorite_courses')
    op.drop_index(op.f('ix_user_favorite_courses_user'), table_name='user_favorite_courses')
    op.drop_table('user_favorite_courses')
    op.drop_table('language_levels')
    op.drop_index(op.f('ix_lesson_views_id'), table_name='lesson_views')
    op.drop_index(op.f('ix_lesson_views_lesson_id'), table_name='lesson_views')
    op.drop_index(op.f('ix_lesson_views_user_id'), table_name='lesson_views')
    op.drop_table('lesson_views')
    op.drop_index(op.f('ix_language_lesson_views_lesson'), table_name='language_lesson_views')
    op.drop_table('language_lesson_views')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_ege_test_questions_id'), table_name='ege_test_questions')
    op.drop_table('ege_test_questions')
    op.drop_index(op.f('ix_reaction_review'), table_name='review_reactions')
    op.drop_index(op.f('ix_reaction_user'), table_name='review_reactions')
    op.drop_index(op.f('ix_review_reactions_id'), table_name='review_reactions')
    op.drop_table('review_reactions')
    op.drop_table('flashcard_decks')
    op.drop_index(op.f('ix_ege_lessons_id'), table_name='ege_lessons')
    op.drop_index(op.f('ix_ege_lessons_slug'), table_name='ege_lessons')
    op.drop_index(op.f('ix_ege_lessons_subject_id'), table_name='ege_lessons')
    op.drop_index(op.f('ix_ege_lessons_subject_unit'), table_name='ege_lessons')
    op.drop_index(op.f('ix_ege_lessons_unit_id'), table_name='ege_lessons')
    op.drop_table('ege_lessons')
    op.drop_index(op.f('ix_course_reviews_course'), table_name='course_reviews')
    op.drop_index(op.f('ix_course_reviews_course_id'), table_name='course_reviews')
    op.drop_index(op.f('ix_course_reviews_id'), table_name='course_reviews')
    op.drop_index(op.f('ix_course_reviews_user'), table_name='course_reviews')
    op.drop_index(op.f('ix_course_reviews_user_id'), table_name='course_reviews')
    op.drop_table('course_reviews')
    op.drop_index(op.f('idx_achievements_user'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_table('language_comment_reactions')
    op.drop_index(op.f('ix_ege_tests_id'), table_name='ege_tests')
    op.drop_table('ege_tests')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('users', sa.Column('registration_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.drop_constraint(op.f('users_equipped_item_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_equipped_item_id_fkey'), 'users', 'shop_items', ['equipped_item_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'registration_ip')
    op.drop_column('users', 'is_verified')
    op.create_table('ege_tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passing_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['ege_lessons.id'], name=op.f('ege_tests_lesson_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ege_tests_pkey')),
    sa.UniqueConstraint('lesson_id', name=op.f('ege_tests_lesson_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ege_tests_id'), 'ege_tests', ['id'], unique=False)
    op.create_table('language_comment_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_like', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['language_comments.id'], name=op.f('language_comment_reactions_comment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('language_comment_reactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('language_comment_reactions_pkey')),
    sa.UniqueConstraint('comment_id', 'user_id', name=op.f('language_comment_reactions_comment_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('context_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_achievements_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_achievements_pkey')),
    sa.UniqueConstraint('user_id', 'reward_type', 'context_id', name=op.f('uq_user_achievement'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('idx_achievements_user'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('course_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('check_rating_range')),
    sa.ForeignKeyConstraint(['course_id'], ['ege_subjects.id'], name=op.f('course_reviews_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('course_reviews_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('course_reviews_pkey')),
    sa.UniqueConstraint('user_id', 'course_id', name=op.f('uq_user_course_review'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_course_reviews_user_id'), 'course_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_course_reviews_user'), 'course_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_course_reviews_id'), 'course_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_course_reviews_course_id'), 'course_reviews', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_reviews_course'), 'course_reviews', ['course_id'], unique=False)
    op.create_table('ege_lessons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('unit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['ege_subjects.id'], name=op.f('ege_lessons_subject_id_fkey')),
    sa.ForeignKeyConstraint(['unit_id'], ['course_units.id'], name=op.f('fk_ege_lessons_unit_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ege_lessons_pkey'))
    )
    op.create_index(op.f('ix_ege_lessons_unit_id'), 'ege_lessons', ['unit_id'], unique=False)
    op.create_index(op.f('ix_ege_lessons_subject_unit'), 'ege_lessons', ['subject_id', 'unit', 'created_at'], unique=False)
    op.create_index(op.f('ix_ege_lessons_subject_id'), 'ege_lessons', ['subject_id'], unique=False)
    op.create_index(op.f('ix_ege_lessons_slug'), 'ege_lessons', ['slug'], unique=True)
    op.create_index(op.f('ix_ege_lessons_id'), 'ege_lessons', ['id'], unique=False)
    op.create_table('flashcard_decks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['ege_lessons.id'], name=op.f('flashcard_decks_lesson_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('flashcard_decks_pkey')),
    sa.UniqueConstraint('lesson_id', name=op.f('flashcard_decks_lesson_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('review_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['course_reviews.id'], name=op.f('review_reactions_review_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('review_reactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('review_reactions_pkey')),
    sa.UniqueConstraint('user_id', 'review_id', name=op.f('uq_user_review_reaction'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_review_reactions_id'), 'review_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_reaction_user'), 'review_reactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_reaction_review'), 'review_reactions', ['review_id'], unique=False)
    op.create_table('ege_test_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['ege_tests.id'], name=op.f('ege_test_questions_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ege_test_questions_pkey'))
    )
    op.create_index(op.f('ix_ege_test_questions_id'), 'ege_test_questions', ['id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('teachers_pkey'))
    )
    op.create_table('language_lesson_views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('viewed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['language_lessons.id'], name=op.f('language_lesson_views_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('language_lesson_views_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('language_lesson_views_pkey')),
    sa.UniqueConstraint('lesson_id', 'user_id', name=op.f('language_lesson_views_lesson_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_language_lesson_views_lesson'), 'language_lesson_views', ['lesson_id'], unique=False)
    op.create_table('lesson_views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['ege_lessons.id'], name=op.f('lesson_views_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('lesson_views_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_views_pkey')),
    sa.UniqueConstraint('user_id', 'lesson_id', name=op.f('uq_user_lesson_view'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_lesson_views_user_id'), 'lesson_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_lesson_views_lesson_id'), 'lesson_views', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_views_id'), 'lesson_views', ['id'], unique=False)
    op.create_table('language_levels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['language_subjects.id'], name=op.f('language_levels_subject_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('language_levels_pkey')),
    sa.UniqueConstraint('subject_id', 'slug', name=op.f('language_levels_subject_id_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_favorite_courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['ege_subjects.id'], name=op.f('user_favorite_courses_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_favorite_courses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_favorite_courses_pkey')),
    sa.UniqueConstraint('user_id', 'course_id', name=op.f('user_favorite_courses_user_id_course_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_favorite_courses_user'), 'user_favorite_courses', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_courses_course'), 'user_favorite_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_fav_user'), 'user_favorite_courses', ['user_id'], unique=False)
    op.create_index(op.f('ix_fav_course'), 'user_favorite_courses', ['course_id'], unique=False)
    op.create_table('flashcard_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_review', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('interval_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ease_factor', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('2.5'), autoincrement=False, nullable=True),
    sa.Column('repetitions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('times_seen', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('times_correct', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_answered', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['flashcards.id'], name=op.f('flashcard_progress_card_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('flashcard_progress_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('flashcard_progress_pkey')),
    sa.UniqueConstraint('user_id', 'card_id', name=op.f('flashcard_progress_user_id_card_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_flashcard_progress_user'), 'flashcard_progress', ['user_id', 'next_review'], unique=False)
    op.create_table('language_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['language_lessons.id'], name=op.f('language_comments_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['language_comments.id'], name=op.f('language_comments_parent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('language_comments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('language_comments_pkey'))
    )
    op.create_index(op.f('ix_language_comments_lesson'), 'language_comments', ['lesson_id'], unique=False)
    op.create_table('user_article_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('user_article_favorites_article_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_article_favorites_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_article_favorites_pkey')),
    sa.UniqueConstraint('user_id', 'article_id', name=op.f('uq_user_article_fav'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_article_fav_user'), 'user_article_favorites', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_article_fav_article'), 'user_article_favorites', ['article_id'], unique=False)
    op.create_table('lesson_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_like', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['ege_lessons.id'], name=op.f('lesson_reactions_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('lesson_reactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_reactions_pkey')),
    sa.UniqueConstraint('user_id', 'lesson_id', name=op.f('uq_user_lesson_reaction'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_lesson_reactions_lesson'), 'lesson_reactions', ['lesson_id'], unique=False)
    op.create_table('user_course_enrollments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['ege_subjects.id'], name=op.f('user_course_enrollments_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_course_enrollments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_course_enrollments_pkey')),
    sa.UniqueConstraint('user_id', 'course_id', name=op.f('user_course_enrollments_user_id_course_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_course_enrollments_user'), 'user_course_enrollments', ['user_id'], unique=False)
    op.create_index(op.f('ix_enroll_user'), 'user_course_enrollments', ['user_id'], unique=False)
    op.create_index(op.f('ix_enroll_course'), 'user_course_enrollments', ['course_id'], unique=False)
    op.create_table('language_subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('language_subjects_pkey')),
    sa.UniqueConstraint('slug', name=op.f('language_subjects_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('language_lesson_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_like', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('language_lesson_reactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('language_lesson_reactions_pkey')),
    sa.UniqueConstraint('user_id', 'lesson_id', name=op.f('language_lesson_reactions_user_id_lesson_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_language_lesson_reactions_user'), 'language_lesson_reactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_language_lesson_reactions_lesson'), 'language_lesson_reactions', ['lesson_id'], unique=False)
    op.create_table('course_units',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('unit_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['ege_subjects.id'], name=op.f('course_units_subject_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('course_units_pkey')),
    sa.UniqueConstraint('subject_id', 'unit_number', name=op.f('course_units_subject_id_unit_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_course_units_subject'), 'course_units', ['subject_id', 'unit_number'], unique=False)
    op.create_table('user_completed_lessons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['ege_lessons.id'], name=op.f('user_completed_lessons_lesson_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_completed_lessons_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_completed_lessons_pkey')),
    sa.UniqueConstraint('user_id', 'lesson_id', name=op.f('uq_user_lesson_completed'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_completed_lessons_id'), 'user_completed_lessons', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('lesson_id IS NOT NULL AND article_id IS NULL OR lesson_id IS NULL AND article_id IS NOT NULL', name=op.f('check_commentable_type')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('comments_article_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['ege_lessons.id'], name=op.f('comments_lesson_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('comments_parent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('comments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_lesson_id'), 'comments', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_article_id'), 'comments', ['article_id'], unique=False)
    op.create_index(op.f('idx_comments_parent'), 'comments', ['parent_id'], unique=False)
    op.create_index(op.f('idx_comments_lesson'), 'comments', ['lesson_id'], unique=False, postgresql_where='(lesson_id IS NOT NULL)')
    op.create_index(op.f('idx_comments_article'), 'comments', ['article_id'], unique=False, postgresql_where='(article_id IS NOT NULL)')
    op.create_table('flashcards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deck_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('front', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('back', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('example', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], name=op.f('flashcards_deck_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('flashcards_pkey'))
    )
    op.create_index(op.f('ix_flashcards_deck_id'), 'flashcards', ['deck_id', 'order_index'], unique=False)
    op.create_table('user_inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acquired_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], name=op.f('user_inventory_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_inventory_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_inventory_pkey')),
    sa.UniqueConstraint('user_id', 'item_id', name=op.f('user_inventory_user_id_item_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_inventory_user'), 'user_inventory', ['user_id'], unique=False)
    op.create_index(op.f('idx_inventory_item'), 'user_inventory', ['item_id'], unique=False)
    op.create_table('user_rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reward_context_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('claimed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_rewards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_rewards_pkey')),
    sa.UniqueConstraint('user_id', 'reward_type', 'reward_context_id', name=op.f('user_rewards_user_id_reward_type_reward_context_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_rewards_user'), 'user_rewards', ['user_id'], unique=False)
    op.create_index(op.f('ix_rewards_type'), 'user_rewards', ['reward_type'], unique=False)
    op.create_table('user_enrollments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_slug', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_slug'], ['ege_subjects.slug'], name=op.f('user_enrollments_course_slug_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_enrollments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_enrollments_pkey'))
    )
    op.create_table('article_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('reaction_type', sa.VARCHAR(length=10), server_default=sa.text("'like'::character varying"), autoincrement=False, nullable=False),
    sa.CheckConstraint("reaction_type::text = ANY (ARRAY['like'::character varying, 'dislike'::character varying]::text[])", name=op.f('article_reactions_reaction_type_check')),
    sa.CheckConstraint("reaction_type::text = ANY (ARRAY['like'::character varying, 'dislike'::character varying]::text[])", name=op.f('chk_reaction_type')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('article_reactions_article_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('article_reactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('article_reactions_pkey')),
    sa.UniqueConstraint('user_id', 'article_id', name=op.f('uq_article_reaction'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', 'article_id', name=op.f('uq_user_article_reaction'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_article_reactions_user_id'), 'article_reactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_reactions_id'), 'article_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_article_reactions_article_id'), 'article_reactions', ['article_id'], unique=False)
    op.create_index(op.f('idx_article_reactions_user'), 'article_reactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_article_reactions_article'), 'article_reactions', ['article_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('articles_pkey')),
    sa.UniqueConstraint('slug', name=op.f('articles_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_articles_topic'), 'articles', ['topic'], unique=False)
    op.create_index(op.f('idx_articles_slug'), 'articles', ['slug'], unique=False)
    op.create_table('course_teachers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['ege_subjects.id'], name=op.f('course_teachers_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('course_teachers_teacher_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('course_teachers_pkey')),
    sa.UniqueConstraint('course_id', 'teacher_id', name=op.f('course_teachers_course_id_teacher_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_course_teachers_teacher'), 'course_teachers', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_course_teachers_course'), 'course_teachers', ['course_id'], unique=False)
    op.create_table('language_lessons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['language_categories.id'], name=op.f('language_lessons_category_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('language_lessons_pkey')),
    sa.UniqueConstraint('category_id', 'slug', name=op.f('language_lessons_category_id_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_language_lessons_category'), 'language_lessons', ['category_id'], unique=False)
    op.create_table('comment_reactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_like', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('comment_reactions_comment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('comment_reactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comment_reactions_pkey')),
    sa.UniqueConstraint('user_id', 'comment_id', name=op.f('comment_reactions_user_id_comment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_comment_reactions_comment'), 'comment_reactions', ['comment_id'], unique=False)
    op.create_table('course_enrollments',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['ege_subjects.id'], name=op.f('course_enrollments_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('course_enrollments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name=op.f('course_enrollments_pkey'))
    )
    op.create_table('shop_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('price > 0', name=op.f('shop_items_price_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('shop_items_pkey'))
    )
    op.create_index(op.f('idx_shop_items_active'), 'shop_items', ['is_active'], unique=False)
    op.create_table('language_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['language_levels.id'], name=op.f('language_categories_level_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('language_categories_pkey')),
    sa.UniqueConstraint('level_id', 'slug', name=op.f('language_categories_level_id_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('test_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['ege_lessons.id'], name=op.f('test_results_lesson_id_fkey')),
    sa.ForeignKeyConstraint(['test_id'], ['ege_tests.id'], name=op.f('test_results_test_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('test_results_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('test_results_pkey'))
    )
    op.create_index(op.f('ix_test_results_user_id'), 'test_results', ['user_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_id'), 'test_results', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_results_lesson_id'), 'test_results', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('idx_test_results_user_test'), 'test_results', ['user_id', 'test_id'], unique=True)
    op.create_index(op.f('idx_test_results_user'), 'test_results', ['user_id'], unique=False)
    op.create_index(op.f('idx_test_results_test'), 'test_results', ['test_id'], unique=False)
    op.create_table('article_views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('article_views_article_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('article_views_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('article_views_pkey'))
    )
    op.create_index(op.f('ix_article_views_user_id'), 'article_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_views_id'), 'article_views', ['id'], unique=False)
    op.create_index(op.f('ix_article_views_article_id'), 'article_views', ['article_id'], unique=False)
    op.create_index(op.f('idx_article_views_unique_daily'), 'article_views', ['user_id', 'article_id', sa.literal_column('date(viewed_at)')], unique=True)
    op.create_index(op.f('idx_article_views_article'), 'article_views', ['article_id'], unique=False)
    op.create_table('ege_subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cover_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('certificate_available', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ege_subjects_pkey'))
    )
    op.create_index(op.f('ix_ege_subjects_slug'), 'ege_subjects', ['slug'], unique=True)
    op.create_index(op.f('ix_ege_subjects_id'), 'ege_subjects', ['id'], unique=False)
    op.create_table('user_equipped_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('equipped_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], name=op.f('user_equipped_items_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_equipped_items_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_equipped_items_pkey')),
    sa.UniqueConstraint('user_id', 'item_id', name=op.f('user_equipped_items_user_id_item_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_equipped_user'), 'user_equipped_items', ['user_id'], unique=False)
    op.create_index(op.f('idx_equipped_item'), 'user_equipped_items', ['item_id'], unique=False)
    # ### end Alembic commands ###
